import { Map as LibreMap, NavigationControl, ScaleControl, addProtocol, setWorkerCount, setWorkerUrl, type GeoJSONSource, type ExpressionSpecification } from 'maplibre-gl';
import { PMTiles, Protocol, SharedPromiseCache } from 'pmtiles';
import type { LineString } from 'geojson';
import { Summary, MM_PER_MILE, classify, readThreshold, thresholdLabel, toMm } from './threshold';
import './style.css';
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';

type Manifest={geographic_scope?:'city'|'ward35';scope_label?:string;bounds?:[[number,number],[number,number]];build_id:string;as_of:string;total_designated_mm:number;segment_count:number;reviewed_segments:number;checksums:Record<string,string>};
type Catalog={sid:number;name:string;cross_streets:string;center:[number,number]};
type Detail={sid:number;name:string;source_cross_streets:string;cross_street_note:string;lb_mm:number;exact:number;gw_mm:number;direction:string;endpoints:string[];review_reason:string;source_date:string;evidence:{label:string;url:string}[];geometry:LineString;run_id?:number};
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const miles=(mm:number)=> (mm/MM_PER_MILE).toFixed(2);
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let xMm=readThreshold(location.search), onlyPassing=false, selected:Detail|undefined, mapReady=false, sequence=0;
let map:LibreMap, summary:Summary, base='', manifest:Manifest;
const details=new globalThis.Map<number,Detail>();
let pending:number|undefined;
$('app').innerHTML=`
<header class="site-header"><div class="brand"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M6 27V7h20M16 27V17h10" stroke="#d4f46f" stroke-width="4" fill="none"/></svg><div><div class="brand-title">Chicago Greenway Audit</div><div class="brand-kicker">Streets, measured differently</div></div></div><div class="header-right"><span class="pilot-tag" id="scope-tag">CITYWIDE INVENTORY</span><button id="share" class="share">Copy link</button></div></header>
<main><aside class="sidebar" aria-label="Greenway driving test"><div class="intro"><div class="eyebrow">Straight-through driving</div><h1>How far can a driver keep going?</h1><p>Test potential cut-through access on designated neighborhood greenways.</p></div>
<section class="control-panel" aria-label="Distance threshold"><label class="threshold-label" for="threshold">Flag streets where a driver can continue straight for at least…</label><div class="number-row"><input id="threshold" type="number" min="0.01" max="20" step="any" inputmode="decimal" aria-describedby="threshold-error threshold-hint"><span>miles</span></div><input id="slider" type="range" min="0.125" max="2" step="0.125" aria-label="Straight-through distance in miles"><div class="range-labels"><span id="slider-min">⅛ mile</span><span id="slider-max">2 miles</span></div><p class="hint" id="threshold-hint">Type any distance from 0.01 to 20 miles.</p><div class="error" id="threshold-error" role="alert"></div></section>
<section class="summary" aria-label="Designated mileage summary"><p class="summary-label">Passes the straight-through driving test</p><div class="summary-value"><strong id="passing-mileage">—</strong><span>mi · <span id="passing-share">—</span></span></div><div class="bar" aria-hidden="true"><span class="bar-pass" id="bar-pass"></span><span class="bar-fail" id="bar-fail"></span><span class="bar-unknown" id="bar-unknown"></span></div><ul class="legend"><li><span class="legend-label"><i class="sample fail"></i><span id="fail-label">At least 0.5 mi</span></span><output id="failing-mileage">—</output></li><li><span class="legend-label"><i class="sample"></i><span id="pass-label">Less than 0.5 mi</span></span><output id="pass-legend">—</output></li><li><span class="legend-label"><i class="sample unknown"></i>Unverified</span><output id="unknown-mileage">—</output></li></ul><label class="filter"><input type="checkbox" id="only-passing">Show only passing segments</label><p class="hint" id="summary-scope">Totals cover the full inventory, including streets outside this view.</p><span class="sr-only" id="summary-announcement" aria-live="polite"></span></section>
<div class="review-note"><strong>Driving analysis is incomplete.</strong> Greenway designations are mapped, but legal motor movements and full driving runs are not yet verified. Gray means unknown, not pass or fail.</div>
<div class="segment-picker"><label for="segments">Inspect a greenway segment</label><select id="segments"><option value="">Choose a street segment…</option></select></div>
<details class="method"><summary>How this test works</summary><p>Once verified, a segment receives the full uninterrupted driving-run distance, including streets beyond the greenway and ward boundary. The longer permitted motor direction controls. Equality fails.</p><p>A known run at least as long as the threshold fails. A shorter run passes only when all relevant directions and endpoints are resolved. Everything else stays unverified.</p><p>This indicates potential cut-through access, not traffic volume or a guarantee of cycling comfort. The faint baseline always shows the designation.</p><p id="as-of"></p><p><a id="manifest-link">Build and sources</a> · <a href="https://data.cityofchicago.org/Transportation/Bike-Routes/hvv9-38ut" target="_blank" rel="noreferrer">Official inventory</a></p></details></aside>
<section class="map-wrap" aria-label="Chicago greenway map"><div id="map"></div><div class="map-top"><div class="map-pill"><strong id="scope-label">Chicago</strong><span id="inventory-label">Loading inventory…</span></div><div class="map-tools"><button id="reset-map">Fit all greenways</button><button id="ward-view">Zoom to Ward 35</button></div></div><div id="selection" class="selection" hidden aria-live="polite"></div><div id="map-empty" class="map-empty" hidden><strong>No verified passing segments</strong><p>Turn off the filter to inspect the unverified designation.</p></div><div class="map-notice" id="map-notice" hidden role="status"></div></section></main>`;
for(const id of ['threshold','slider','only-passing','segments'])$(id).setAttribute('disabled','');
function writeUrl(){const u=new URL(location.href);u.searchParams.set('x_mm',String(xMm));if(map){const c=map.getCenter();u.searchParams.set('map',`${map.getZoom().toFixed(3)},${c.lat.toFixed(6)},${c.lng.toFixed(6)}`);}history.replaceState(null,'',u);}
function paint(){if(!mapReady)return;const color:ExpressionSpecification=['case',['>=',['get','lb_mm'],xMm],'#c43d3d',['==',['get','exact'],1],'#187b55','#707e87'];const pass:ExpressionSpecification=['all',['<',['get','lb_mm'],xMm],['==',['get','exact'],1]];
 map.setPaintProperty('greenways','line-color',color);map.setPaintProperty('greenways','line-opacity',onlyPassing?['case',pass,1,0]:1);
 map.setFilter('unverified',['all',['<',['get','lb_mm'],xMm],['==',['get','exact'],0]]);map.setLayoutProperty('unverified','visibility',onlyPassing?'none':'visible');
 map.setFilter('fail-center',['>=',['get','lb_mm'],xMm]);map.setLayoutProperty('fail-center','visibility',onlyPassing?'none':'visible');
 if(selected&&onlyPassing&&classify(selected.lb_mm,selected.exact,xMm)!=='pass')clearSelection();
}
function render(){const totals=summary.at(xMm);const label=thresholdLabel(xMm);$('passing-mileage').textContent=miles(totals.passing);$('passing-share').textContent=`${(totals.share*100).toFixed(0)}%`;$('pass-legend').textContent=`${miles(totals.passing)} mi`;$('failing-mileage').textContent=`${miles(totals.failing)} mi`;$('unknown-mileage').textContent=`${miles(totals.unknown)} mi`;$('fail-label').textContent=`At least ${label} mi`;$('pass-label').textContent=`Less than ${label} mi`;
 for(const [id,value] of [['bar-pass',totals.passing],['bar-fail',totals.failing],['bar-unknown',totals.unknown]] as const)$(id).style.width=`${totals.total?value/totals.total*100:0}%`;
 $('map-empty').hidden=!(onlyPassing&&totals.passing===0);$('summary-announcement').textContent=`${miles(totals.passing)} miles pass, ${miles(totals.failing)} fail, ${miles(totals.unknown)} unverified.`;
 paint();if(selected)renderDetail(selected);writeUrl();}
function updateThreshold(mm:number, updateNumber=true){xMm=mm;const milesValue=mm/MM_PER_MILE;const slider=$<HTMLInputElement>('slider');slider.min=String(Math.min(0.125,milesValue));slider.max=String(Math.max(2,milesValue));slider.step='any';slider.value=String(milesValue);slider.setAttribute('aria-valuetext',`${thresholdLabel(mm)} miles`);$('slider-min').textContent=Number(slider.min)===.125?'⅛ mile':`${Number(slider.min).toFixed(2)} mi`;$('slider-max').textContent=`${Number(slider.max).toFixed(2).replace(/\.00$/,'')} miles`;if(updateNumber)$<HTMLInputElement>('threshold').value=thresholdLabel(mm);$('threshold-error').textContent='';$<HTMLInputElement>('threshold').removeAttribute('aria-invalid');render();}
function schedule(mm:number,updateNumber=true){if(pending!==undefined)cancelAnimationFrame(pending);pending=requestAnimationFrame(()=>{pending=undefined;updateThreshold(mm,updateNumber);});}
function clearSelection(){sequence++;selected=undefined;$('selection').hidden=true;$<HTMLSelectElement>('segments').value='';if(mapReady){map.setFilter('selected',['==',['get','sid'],-1]);(map.getSource('run') as GeoJSONSource).setData({type:'FeatureCollection',features:[]});}}
function renderDetail(d:Detail){const status=classify(d.lb_mm,d.exact,xMm);const text={pass:'Passes the test',fail:'At least the threshold',unknown:'Unverified'}[status];$('selection').hidden=false;$('selection').innerHTML=`<button class="close" id="close-detail" aria-label="Close segment details">×</button><div class="status-label ${status}">${text}</div><h2>${escape(d.name.toLowerCase())}</h2><p class="cross">${escape(d.source_cross_streets.toLowerCase())}<br>Source designation</p><div class="detail-distance">${!d.exact&&d.lb_mm===0?'Driving run unverified':`${d.exact?'':'At least '}${miles(d.lb_mm)} miles`}</div><p>${escape(d.review_reason)}</p><dl><dt>Direction</dt><dd>${escape(d.direction)}</dd><dt>Upstream</dt><dd>${escape(d.endpoints[0])}</dd><dt>Downstream</dt><dd>${escape(d.endpoints[1])}</dd><dt>Designation</dt><dd>${miles(d.gw_mm)} mi · selected interval</dd><dt>Source date</dt><dd>${escape(d.source_date)}</dd></dl><p>${escape(d.cross_street_note)}</p>${d.run_id!==undefined?'<p>Blue line: full controlling driving run.</p>':''}${d.evidence.filter(e=>/^https:\/\//.test(e.url)).map(e=>`<a href="${escape(e.url)}" target="_blank" rel="noreferrer">${escape(e.label)}</a>`).join(' · ')}`;$('close-detail').onclick=clearSelection;}
async function fetchAsset(path:string):Promise<ArrayBuffer>{const r=await fetch(`${base}/${path}`);if(!r.ok)throw new Error(`Could not load ${path}.`);const bytes=await r.arrayBuffer();const expected=manifest?.checksums[path];if(expected){const digest=await crypto.subtle.digest('SHA-256',bytes);const actual=Array.from(new Uint8Array(digest),v=>v.toString(16).padStart(2,'0')).join('');if(actual!==expected)throw new Error(`Data checksum mismatch: ${path}`);}return bytes;}
async function selectSegment(sid:number,fly=false){const request=++sequence;try{let d=details.get(sid);if(!d){d=JSON.parse(new TextDecoder().decode(await fetchAsset(`details/${sid}.json`))) as Detail;details.set(sid,d);if(details.size>12)details.delete(details.keys().next().value!);}else{details.delete(sid);details.set(sid,d);}if(request!==sequence)return;if(onlyPassing&&classify(d.lb_mm,d.exact,xMm)!=='pass'){clearSelection();return;}const run=d.run_id===undefined?{type:'FeatureCollection',features:[]}:JSON.parse(new TextDecoder().decode(await fetchAsset(`runs/${d.run_id}.json`)));if(request!==sequence)return;if(mapReady)(map.getSource('run') as GeoJSONSource).setData(run);selected=d;$<HTMLSelectElement>('segments').value=String(sid);renderDetail(d);if(mapReady){map.setFilter('selected',['==',['get','sid'],sid]);if(fly)map.easeTo({center:d.geometry.coordinates[0] as [number,number],zoom:15,duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:500});}}catch(e){notice(String(e));}}
function notice(message:string){$('map-notice').hidden=false;$('map-notice').textContent=message;}
const number=$<HTMLInputElement>('threshold');number.oninput=()=>{try{const mm=toMm(number.valueAsNumber);schedule(mm,false);}catch(e){if(pending!==undefined){cancelAnimationFrame(pending);pending=undefined;}number.setAttribute('aria-invalid','true');$('threshold-error').textContent=(e as Error).message;}};number.onchange=()=>{if(number.getAttribute('aria-invalid')!=='true')number.value=thresholdLabel(toMm(number.valueAsNumber));};
$<HTMLInputElement>('slider').oninput=e=>{const value=Number((e.target as HTMLInputElement).value);const slider=$<HTMLInputElement>('slider');const snapped=Math.min(Number(slider.max),Math.max(Number(slider.min),Math.round(value/.125)*.125));schedule(toMm(snapped));};
$<HTMLInputElement>('slider').onkeydown=e=>{if(['ArrowLeft','ArrowDown','ArrowRight','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const slider=$<HTMLInputElement>('slider');const next=e.key==='Home'?Number(slider.min):e.key==='End'?Number(slider.max):xMm/MM_PER_MILE+(['ArrowLeft','ArrowDown'].includes(e.key)?-.125:.125);schedule(toMm(Math.max(.01,Math.min(20,next))));}};
$<HTMLInputElement>('only-passing').onchange=e=>{onlyPassing=(e.target as HTMLInputElement).checked;render();};
$('share').onclick=async()=>{try{if(pending!==undefined){cancelAnimationFrame(pending);pending=undefined;const value=number.valueAsNumber;if(Number.isFinite(value))updateThreshold(toMm(value));}writeUrl();await navigator.clipboard.writeText(location.href);$('share').textContent='Link copied';setTimeout(()=>$('share').textContent='Copy link',1800);}catch{notice('Copy the address from your browser to share this view.');}};
$<HTMLSelectElement>('segments').onchange=e=>{const id=Number((e.target as HTMLSelectElement).value);if(id)void selectSegment(id,true);else clearSelection();};
const wardBounds:[[number,number],[number,number]]=[[-87.734,41.913],[-87.693,41.968]];
$('reset-map').onclick=()=>map?.fitBounds(manifest.bounds??wardBounds,{padding:45,duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:500});
$('ward-view').onclick=()=>map?.fitBounds(wardBounds,{padding:45,duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:500});
async function start(){try{
 const pointer=await fetch('/current.json').then(r=>{if(!r.ok)throw new Error('Inventory unavailable');return r.json();});base=`/builds/${pointer.build_id}`;
 manifest=await fetch(`${base}/manifest.json`).then(r=>r.json());summary=new Summary(await fetchAsset('summary.bin'));
 const scopeLabel=manifest.scope_label??'Ward 35';$('scope-label').textContent=scopeLabel;$('scope-tag').textContent=manifest.geographic_scope==='city'?'CITYWIDE INVENTORY':'WARD 35 PILOT';$('reset-map').textContent=manifest.geographic_scope==='city'?'Fit all Chicago greenways':'Fit pilot area';$('ward-view').hidden=manifest.geographic_scope!=='city';$('summary-scope').textContent=`Totals cover ${scopeLabel}, including streets outside this view.`;
 if(summary.total!==manifest.total_designated_mm)throw new Error('Manifest total differs from summary.');
 $('inventory-label').textContent=`${miles(summary.total)} mi designated`;$('as-of').textContent=`Designation inventory: ${manifest.as_of}. ${manifest.reviewed_segments} of ${manifest.segment_count} intervals have reviewed inputs.`;if(manifest.reviewed_segments>0){const note=document.querySelector('.review-note')!;note.textContent=`${manifest.reviewed_segments} intervals have reviewed inputs. Gray segments still have unresolved conditions.`;}$<HTMLAnchorElement>('manifest-link').href=`${base}/manifest.json`;
 const catalog:Catalog[]=JSON.parse(new TextDecoder().decode(await fetchAsset('catalog.json')));
 const select=$<HTMLSelectElement>('segments');const groups=new globalThis.Map<string,HTMLOptGroupElement>();catalog.sort((a,b)=>a.name.localeCompare(b.name)||a.sid-b.sid);for(const item of catalog){let group=groups.get(item.name);if(!group){group=document.createElement('optgroup');group.label=item.name.toLowerCase();groups.set(item.name,group);select.append(group);}const option=document.createElement('option');option.value=String(item.sid);option.textContent=`${item.name.toLowerCase()} · segment ${item.sid}`;group.append(option);}
 for(const id of ['threshold','slider','only-passing','segments'])$(id).removeAttribute('disabled');
 updateThreshold(xMm);
 setWorkerUrl(workerUrl);setWorkerCount(2);const protocol=new Protocol();addProtocol('pmtiles',protocol.tile);const archive=new PMTiles(new URL(`${base}/greenways.pmtiles`,location.origin).href,new SharedPromiseCache(16));protocol.add(archive);
 const position=new URLSearchParams(location.search).get('map')?.split(',').map(Number);const valid=position?.length===3&&position.every(Number.isFinite)&&position[0]>=8&&position[0]<=19&&Math.abs(position[1])<=85&&Math.abs(position[2])<=180;
 map=new LibreMap({container:'map',style:'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',center:valid?[position![2],position![1]]:[-87.67,41.84],zoom:valid?position![0]:9.5,bounds:valid?undefined:manifest.bounds,fitBoundsOptions:{padding:45},minZoom:8,maxZoom:19,maxTileCacheSize:64,maxTileCacheZoomLevels:3,renderWorldCopies:false,attributionControl:{compact:true},canvasContextAttributes:{antialias:true}});
 map.addControl(new NavigationControl({showCompass:false}),'top-right');map.addControl(new ScaleControl({unit:'imperial'}),'bottom-left');
 map.on('error',e=>{console.error(e.error);notice('Some map tiles could not load. The mileage summary and street selector remain available.');});
 map.on('load',()=>{
 if(manifest.geographic_scope!=='city'){map.addSource('ward',{type:'geojson',data:`${base}/ward35.geojson`});map.addLayer({id:'ward-fill',type:'fill',source:'ward',paint:{'fill-color':'#3c7c61','fill-opacity':.045}});map.addLayer({id:'ward-boundary',type:'line',source:'ward',paint:{'line-color':'#638b76','line-opacity':.45,'line-width':1.5,'line-dasharray':[4,4]}});}
 map.addSource('greenways',{type:'vector',url:`pmtiles://${new URL(`${base}/greenways.pmtiles`,location.origin).href}`,attribution:'Bike routes: City of Chicago'});
 map.addSource('run',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'run-path',source:'run',type:'line',paint:{'line-color':'#225ea8','line-width':4,'line-opacity':.65}});
 const line={source:'greenways','source-layer':'greenways',type:'line' as const,layout:{'line-cap':'round' as const,'line-join':'round' as const}};
 map.addLayer({...line,id:'baseline',paint:{'line-color':'#99aaa0','line-width':9,'line-opacity':.3}});
 map.addLayer({...line,id:'selected',filter:['==',['get','sid'],-1],paint:{'line-color':'#164ea3','line-width':12,'line-opacity':.6}});
 map.addLayer({...line,id:'greenways',paint:{'line-color':'#707e87','line-width':5,'line-color-transition':{duration:0},'line-opacity-transition':{duration:0}}});
 map.addLayer({...line,id:'unverified',paint:{'line-color':'#f6f8f7','line-width':2,'line-dasharray':[2,3]}});
 map.addLayer({...line,id:'fail-center',paint:{'line-color':'#fff','line-width':1}});
 map.addLayer({...line,id:'hit',paint:{'line-width':18,'line-opacity':0}});
 mapReady=true;paint();if(selected)map.setFilter('selected',['==',['get','sid'],selected.sid]);
 map.on('click','hit',e=>{const f=e.features?.[0];if(!f)return;const p=f.properties;if(onlyPassing&&classify(p.lb_mm,p.exact,xMm)!=='pass')return;void selectSegment(Number(p.sid));});map.on('mouseenter','hit',()=>{map.getCanvas().style.cursor='pointer';});map.on('mouseleave','hit',()=>{map.getCanvas().style.cursor='';});
 });map.on('moveend',writeUrl);
 const context=(document as Document&{modelContext?:{registerTool:(tool:unknown)=>Promise<void>}}).modelContext;
 if(context)void context.registerTool({name:'set_driving_threshold',description:'Set the distance threshold in miles and return the updated designated mileage totals.',inputSchema:{type:'object',properties:{miles:{type:'number',minimum:.01,maximum:20}},required:['miles'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||!('miles' in input)||typeof input.miles!=='number')throw new Error('miles must be a number');updateThreshold(toMm(input.miles));return{x_mm:xMm,...summary.at(xMm)};}}).catch(console.error);
 }catch(e){notice(`Could not load the audit. ${String(e)}`);$('inventory-label').textContent='Data unavailable';for(const id of ['threshold','slider','only-passing','segments'])$(id).setAttribute('disabled','');}}
void start();
